# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.enviomail_service:
        class: AppBundle\Services\EnviomailService
        arguments: ["@mailer"]

    app.twig_extension.edad_usuario_extension:
        class: AppBundle\Twig\EdadUsuarioExtension
        tags:
            - { name: twig.extension }
    
    app.datatable.curriculum:
        class: BackendBundle\Datatables\CurriculumDatatable
        parent: sg_datatables.datatable.abstract        
    
