<?php

namespace BackendBundle\Repository;

/**
 * AptitudesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AptitudesRepository extends \Doctrine\ORM\EntityRepository
{
}
