<?php

namespace BackendBundle\Repository;

/**
 * EnfermedadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EnfermedadesRepository extends \Doctrine\ORM\EntityRepository
{
}
