<?php

namespace BackendBundle\Repository;

/**
 * EstudiosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EstudiosRepository extends \Doctrine\ORM\EntityRepository
{
}
