<?php

namespace BackendBundle\Repository;

/**
 * ExperienciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienciaRepository extends \Doctrine\ORM\EntityRepository
{
}
