<?php

namespace BackendBundle\Repository;

/**
 * IdiomasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdiomasRepository extends \Doctrine\ORM\EntityRepository
{
}
