<?php

namespace BackendBundle\Repository;

/**
 * InteresesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteresesRepository extends \Doctrine\ORM\EntityRepository
{
}
