<?php

namespace BackendBundle\Repository;

/**
 * LicenciaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LicenciaRepository extends \Doctrine\ORM\EntityRepository
{
}
