<?php

namespace BackendBundle\Repository;

/**
 * RazaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RazaRepository extends \Doctrine\ORM\EntityRepository
{
}
