<?php

namespace BackendBundle\Repository;

/**
 * ReligionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReligionRepository extends \Doctrine\ORM\EntityRepository
{
}
