<?php

namespace BackendBundle\Repository;

/**
 * ResponsabilidadesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResponsabilidadesRepository extends \Doctrine\ORM\EntityRepository
{
}
