<?php

namespace BackendBundle\Repository;

/**
 * SectorViviendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SectorViviendaRepository extends \Doctrine\ORM\EntityRepository
{
}
