<?php

namespace BackendBundle\Repository;

/**
 * SignoZodiacoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SignoZodiacoRepository extends \Doctrine\ORM\EntityRepository
{
}
