<?php

namespace BackendBundle\Repository;

/**
 * ViviendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ViviendaRepository extends \Doctrine\ORM\EntityRepository
{
}
